// Real Android WebView acceptance for persistent page and prepared runtime.
const {execFileSync}=require('node:child_process');
const fs=require('node:fs');
const base=(process.env.HOMER_ACCEPTANCE_BASE||'http://172.24.5.154:8080').replace(/\/$/,'');
const device=process.env.HOMER_ACCEPTANCE_DEVICE||'emulator-5554';
const pkg=process.env.HOMER_ACCEPTANCE_PACKAGE||'org.nebula.horizon.composeai.uireview';
const adb=(...args)=>execFileSync('D:/Android/Sdk/platform-tools/adb.exe',['-s',device,...args],{encoding:'utf8'}).trim();
const pause=ms=>new Promise(r=>setTimeout(r,ms));
let ws,seq=0;const pending=new Map();
async function findTarget(predicate){for(let i=0;i<100;i++){let pid='';try{pid=adb('shell','pidof',pkg)}catch{}if(pid)try{adb('forward','tcp:18225','localabstract:webview_devtools_remote_'+pid)}catch{}try{const list=await(await fetch('http://127.0.0.1:18225/json/list')).json();const target=list.find(predicate);if(target)return target}catch{}await pause(150)}throw Error('Missing expected Android WebView page')}
async function connect(predicate){ws?.close();const target=await findTarget(predicate);ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}})}
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout: '+method))},20000);pending.set(id,m=>{clearTimeout(timer);m.error?reject(Error(m.error.message)):resolve(m.result)});ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||'device evaluation failed');return r.result?.value};
async function wait(expression){for(let i=0;i<120;i++){if(await evaluate(expression))return;await pause(150)}throw Error('State did not become ready: '+expression)}
async function touch(selector){const pt=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('missing selector');e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt]});await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
(async()=>{let stage='start';try{await connect(t=>t.url.startsWith(base+'/app/'));stage='open histories';await evaluate(`setTimeout(()=>location.assign('/app/histories.html'),0);true`);await connect(t=>t.url.startsWith(base+'/app/histories.html'));await wait(`document.readyState==='complete'&&document.querySelector('.history-row__main')?.offsetWidth>0`);const historyCount=await evaluate(`document.querySelectorAll('.history-row__main').length`);if(!historyCount)throw Error('No existing history rows');adb('shell','am','force-stop',pkg);adb('shell','am','start','-n',pkg+'/org.nebula.horizon.composeai.ctf.HomerActivity');stage='restore histories';await connect(t=>t.url.startsWith(base+'/app/histories.html'));await wait(`document.querySelector('.history-row__main')?.offsetWidth>0`);const clicked=Date.now();await touch('.history-row__main');stage='bind history';await connect(t=>t.url.startsWith(base+'/app/chat.html'));await wait(`document.body.classList.contains('is-ready')&&!!document.querySelector('#dialogue-frame')?.contentWindow.HomerMemoryBooks`);const historyToReadyMs=Date.now()-clicked;const prepared=await evaluate(`(()=>{const w=document.querySelector('#dialogue-frame').contentWindow;const d=document.querySelector('#dialogue-frame').contentDocument;return {messages:d.querySelectorAll('#chat .mes').length,hasCharacter:w.SillyTavern.getContext().characterId!=null,hasMemory:!!w.HomerMemoryBooks,marks:w.performance.getEntriesByType('mark').map(m=>({name:m.name,ms:Math.round(m.startTime)})).filter(m=>/bind|session|card|bootstrap|ready|prewarm/.test(m.name))}})()`);if(!prepared.messages)throw Error('History restored without real messages');stage='open memory';const memory=await evaluate(`(async()=>{const f=document.querySelector('#dialogue-frame'),w=f.contentWindow,d=f.contentDocument,start=w.performance.now();return await new Promise((resolve,reject)=>{const observer=new w.MutationObserver(()=>{const home=d.querySelector('.stmb-popup[open] .homer-memory-home');if(home?.offsetWidth){observer.disconnect();clearTimeout(timer);resolve({openMs:Math.round(w.performance.now()-start),messages:d.querySelectorAll('#chat .mes').length})}});const timer=setTimeout(()=>{observer.disconnect();reject(Error('memory did not open'))},5000);observer.observe(d.body,{subtree:true,childList:true,attributes:true});d.querySelector('#homer-open-memory-books').click()})})()`);if(!memory.messages)throw Error('Memory opened without restored messages');fs.mkdirSync('output/connectivity-r24',{recursive:true});const result={base,device,pkg,historyCount,historyToReadyMs,prepared,memory};fs.writeFileSync('output/connectivity-r24/native-prepared-local.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{ws?.close()}})().catch(e=>{console.error(stage+': '+e.message);process.exitCode=1});